# -*- coding: utf-8 -*-
"""Embedding_extraction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYy7pIft3iuLOoSxUGuzEOzLVoQHOPFZ

## assumptions

1. Please consider that my model is not enterprise, on test set get 85% of accuracy, some rare classes are a issue because original dataset have unbalance distribution and not enough data for hard classification task

 2. I'm developing a best-effort approach for a real-time microservice that performs drift detection filtering to be deploy into the 5G layer

## Drift detection

Using another heavy autoencoder model can not be ideal for limited HW scenario.

For this reason, I am trying to find out how to execute a less expensive drift detection operation before developing a microservice for the 5G k8s Layer.

I am interested into a portable and general solution.

---------------------------------------------------------------------------

> I want use a geometric approach.

----------------------------------------------------------------------------
This project has been devided around four main stages:
1. STAGE 1: Embedding extraction using a CNN model developed by me
2. STAGE 2: Visualize the embedding distribution and useful patterns
2. STAGE 3: Develop a robust dynamic thresholding policy to distinguish drifted data from clean/healthy data
2. STAGE 4: Test the thresholding policy using a sliding window scenario and gather performance metrics such as accuracy, precision, recall, and F1-score
3. STAGE 5: Use the OOD samples to retrain and tune the model
----------------------------------------------------------------------------

### I am interested in semantic drift

Discover how the model behaves by analyzing its embeddings when given:

- In-domain images: Grocery items with unusual or peculiar shapes.
- Out-of-domain images: Images completely outside the grocery domain.

Images that are very close to the original dataset are difficult to filter out because deep learning models generalize well. Forcing the model to change this behavior could lead to overfitting and a drop in performance.

Therefore, the focus is on detecting distinct semantic drift using images with unique and interesting features.

## STAGE 1
"""

!pip install image-classifiers
!git clone https://github.com/marcusklasson/GroceryStoreDataset.git # training dataset

import os
import json
import random
import numpy as np
import time
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image, ImageOps
from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download
import tensorflow as tf
import keras
from keras import Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from classification_models.tfkeras import Classifiers
from google.colab import drive
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
import plotly.express as px
import seaborn as sns
from sklearn.neighbors import NearestNeighbors

from huggingface_hub import snapshot_download
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from collections import deque
from sklearn.mixture import GaussianMixture
from sklearn.metrics import (
    silhouette_score, confusion_matrix, ConfusionMatrixDisplay,
    classification_report, accuracy_score, precision_score,
    recall_score, f1_score
)
from scipy.stats import norm
from sklearn.metrics import auc, precision_recall_curve, roc_curve

"""Grocery Store detection is my CNN model for testing.

Experiment conclusion are not related to the model but are general.
"""

REPO_ID = "tomasconti/Drift_Detection"
print("Download RestNet18 model")
config_path = hf_hub_download(repo_id=REPO_ID, filename="resnet18_v1/config.json")
weights_path = hf_hub_download(repo_id=REPO_ID, filename="resnet18_v1/model.weights.h5")
with open(config_path, "r") as f:
    model_config = json.load(f)
model = keras.utils.deserialize_keras_object(model_config)
model.load_weights(weights_path)
print("\nRestNet18 loaded")
model.summary()
ResNet18, preprocess_input = Classifiers.get('resnet18') # need of preprocess_input for the ImageDataGenerator, creating streaming sample batch
embedding_extractor = Model(inputs=model.input, outputs=model.get_layer("embedding_layer").output )

ROOT_DIR = "/content/GroceryStoreDataset/dataset/"
def process_dataframe(df, root_dir):
    df['path'] = df['path'].apply(lambda x: os.path.join(root_dir, x))
    df['fine_label'] = df['fine_label'].astype(str)
    return df

train_df = pd.read_csv(os.path.join(ROOT_DIR, "train.txt"), header=None, sep=",", names=['path', 'fine_label', 'coarse_label'])
val_df = pd.read_csv(os.path.join(ROOT_DIR, "val.txt"), header=None, sep=",",names=['path', 'fine_label', 'coarse_label'])
test_df = pd.read_csv(os.path.join(ROOT_DIR, "test.txt"), header=None, sep=",", names=['path', 'fine_label', 'coarse_label'])

for df in (train_df, val_df, test_df):
    df.drop(columns=["coarse_label"], inplace=True)

train_df = process_dataframe(train_df, ROOT_DIR)
val_df = process_dataframe(val_df, ROOT_DIR)
test_df = process_dataframe(test_df, ROOT_DIR)
##################################################################################################################################################
"""
classes_to_remove = ['10', '16', '26', '27', '32', '33', '4', '63', '73', '74', '8', '18', '22']
train_df = train_df[~train_df['fine_label'].isin(classes_to_remove)]
val_df   = val_df[~val_df['fine_label'].isin(classes_to_remove)]
test_df  = test_df[~test_df['fine_label'].isin(classes_to_remove)]
print(f"Remaining classes in Train: {train_df['fine_label'].nunique()}")
print(f"Remaining classes in Val:   {val_df['fine_label'].nunique()}")
print(f"Remaining classes in Test:  {test_df['fine_label'].nunique()}")
"""
#######################"###########################################################################################################################
combined_df = pd.concat([train_df, val_df], ignore_index=True) #This operation has been explained into the cnn model dev. I need beacause valset does not have all the classes

train_new, val_new = train_test_split(
    combined_df,
    test_size=0.20,
    stratify=combined_df['fine_label'],
    random_state=42
)

print(f"Train: {len(train_new)} | Val: {len(val_new)} | Test: {len(test_df)}")
print(f"Number of fine-grained classes: {combined_df['fine_label'].nunique()}\n")

print( len(train_df['fine_label'].unique()))
print(train_df['fine_label'].unique())

print( len(val_df['fine_label'].unique()))
print(val_df['fine_label'].unique())

print( len(test_df['fine_label'].unique()))
print(test_df['fine_label'].unique())

print( len(train_new['fine_label'].unique()))
print( len(val_new['fine_label'].unique()))
print( len(test_df['fine_label'].unique()))

train_new.head(5)

"""Idea try to delate from the original dataset these classes that are problematic beacuse rare and with out enough samples

from tensorflow import keras
embedding_extractor = keras.models.load_model("/content/drive/MyDrive/resnet18_68C_embedding_layer_v4.keras")
print("Model loaded successfully!")
"""

def create_generator_from_dataframe(df, batch_size=32):
    datagen = ImageDataGenerator(preprocessing_function=preprocess_input) #ideal to define data streaming flow to get into the models
    # 256 x256 becasue the model first layer already resize the imagine into 224 an 224
    #lazily-loaded data stream
    return datagen.flow_from_dataframe( dataframe=df, x_col='path', y_col='fine_label', target_size=(256, 256), batch_size=64, class_mode='categorical', shuffle=False, validate_filenames=False )
train_gen = create_generator_from_dataframe(train_new)
val_gen   = create_generator_from_dataframe(val_new)
test_gen  = create_generator_from_dataframe(test_df)

"""If you want to load the dataset from the local directory use this cell"""

"""
YOGURT_PATH = "/content/drive/MyDrive/Yogurt "
STILL_WATER_PATH = "/content/drive/MyDrive/Still_water_images"
def plot_random_images_inline(folder_path, title_prefix):

    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.png', '.jpg'))] # extract all the valids file name into the dir path

    num_to_sample = min(3, len(files)) #peack random 3
    random_files = random.sample(files, num_to_sample)

    fig, axes = plt.subplots(1, num_to_sample, figsize=(15, 5))
    for i, img_name in enumerate(random_files):
        img = Image.open(os.path.join(folder_path, img_name)) #open the random file name images and plot it
        img = ImageOps.exif_transpose(img)

        axes[i].imshow(img)
        axes[i].set_title(f"{title_prefix}: {img_name}", fontsize=10)
        axes[i].axis('off')

    plt.tight_layout()
    plt.show()

plot_random_images_inline(YOGURT_PATH, "Yogurt")
plot_random_images_inline(STILL_WATER_PATH, "Still water")
"""
"""
#preprocess_input -----> allow the preprocessing operation needed for restnest 18 elaboration (example standard scaling ...)
def create_generator_from_dataframe(df, batch_size=32):
    datagen = ImageDataGenerator(preprocessing_function=preprocess_input) #ideal to define data streaming flow to get into the models
    # 256 x256 becasue the model first layer already resize the imagine into 224 an 224
    return datagen.flow_from_dataframe( dataframe=df, x_col='path', y_col='fine_label', target_size=(256, 256), batch_size=batch_size, class_mode='categorical', shuffle=False, validate_filenames=False )

def create_generator_from_folder(folder_path, batch_size=32):
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.png', '.jpg'))]

    df = pd.DataFrame({'path': [os.path.join(folder_path, f) for f in image_files]}) #extract the absolute path of images

    datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

    return datagen.flow_from_dataframe( dataframe=df, x_col='path', y_col=None, target_size=(256, 256), batch_size=batch_size, class_mode=None, shuffle=False, validate_filenames=False )

train_gen = create_generator_from_dataframe(train_new)
val_gen   = create_generator_from_dataframe(val_new)
test_gen  = create_generator_from_dataframe(test_df)

yogurt_gen = create_generator_from_folder(YOGURT_PATH)
water_gen  = create_generator_from_folder(STILL_WATER_PATH)
"""

"""Loading the project dataset from my hugging face repository"""

#laod the hugging face repo into LOCAL_REPO
#/root/.cache/huggingface/hub/models--tomasconti--Drift_Detection/snapshots/1ec8152c78669....
REPO_ID = "tomasconti/Drift_Detection"
folders_to_download = [
    "S*/*",
    "Y*/*",
    "E*/*"
]
LOCAL_REPO = snapshot_download( repo_id=REPO_ID, repo_type="model", allow_patterns=folders_to_download )
print("Repo loaded into :", LOCAL_REPO)
def get_local_files(folder_keyword):
    image_files = []
    keyword = folder_keyword.lower()

    for root, _, filenames in os.walk(LOCAL_REPO): #recursion looking for the dir with all that that start by keyward
        if keyword in root.lower():
            #print(f"\n root fine out ->  {root.lower()}")
            #print(f"\n file system fine out ->  {filenames}")
            for filename in filenames: #for each file
                if filename.lower().endswith((".png", ".jpg")): #check if it is a images
                    image_files.append(os.path.join(root, filename)) #laod it

    return sorted(image_files)


def create_generator_from_repo_v2(folder_name, batch_size=32):
    file_paths = get_local_files(folder_name) #go into the folder

    if not file_paths:
        raise ValueError(
            f" ERROR no images'{folder_name}'."
        )

    print(f"\n {folder_name}: with inside {len(file_paths)} imagies")

    df = pd.DataFrame({ "path": file_paths  })

    datagen = ImageDataGenerator( preprocessing_function=preprocess_input )

    return datagen.flow_from_dataframe(
        dataframe=df,
        x_col="path",
        y_col=None,
        target_size=(256, 256),
        batch_size=64,
        class_mode=None,
        shuffle=False,
        validate_filenames=False
    )


for cls in ["Still_water_images", "Yogurt", "Eags"]:
    print(cls, len(get_local_files(cls)))
#return the DirectoryIterator class for each set, lazily-loaded datastream
water_gen = create_generator_from_repo_v2("Still_water_images")
yogurt_gen = create_generator_from_repo_v2("Yogurt")
eags_gen = create_generator_from_repo_v2("Eags")

"""
Is important to consider different position and setting of items

The eggs cover sometimes is close (very important)"""

def plot_grid_from_generators(generators_dict, num_samples):

    categories = list(generators_dict.keys())
    n_cats = len(categories)
    fig, axes = plt.subplots(n_cats, num_samples, figsize=(num_samples * 4, n_cats * 4))

    if n_cats == 1 and num_samples == 1: axes = [[axes]]
    elif n_cats == 1: axes = [axes]
    elif num_samples == 1: axes = [[ax] for ax in axes]

    for row, cat in enumerate(categories):
        gen = generators_dict[cat]

        df_files = gen.filenames


        actual_samples = min(num_samples, len(df_files))
        sample_files = random.sample(df_files, actual_samples)

        for col, file_path in enumerate(sample_files):
            img = Image.open(file_path)
            img = ImageOps.exif_transpose(img)

            axes[row][col].imshow(img)
            axes[row][col].set_title(f"{cat}", fontsize=12)
            axes[row][col].axis('off')

        for col in range(actual_samples, num_samples):
            axes[row][col].axis('off')

    plt.tight_layout()
    plt.show()
#dictionary
my_generators = {  "Still Water": water_gen, "Yogurt": yogurt_gen, "Eags": eags_gen }
plot_grid_from_generators(my_generators, num_samples=10)

my_generators2 = {  "Train": train_gen}
plot_grid_from_generators(my_generators2, num_samples=10)

"""After loaded all images extract embeddings from the model's final layer.

Embeddings are vector representations of items in the model's latent feature space.
"""

def extract_and_save(generator, name):
    generator.reset()
    embeddings = embedding_extractor.predict(generator, verbose=1) #model get in is a image streaming
    np.save(f"/content/{name}_embeddings.npy", embeddings)
    print(f"Saved {name}_embeddings.npy and hape: {embeddings.shape}")
#lazily-loaded stream as input to models
extract_and_save(train_gen, "grocery_train")
extract_and_save(val_gen,   "grocery_val")
extract_and_save(test_gen,  "grocery_test")
extract_and_save(yogurt_gen, "yogurt")
extract_and_save(water_gen,  "still_water")
extract_and_save(eags_gen,  "egg")

"""## STAGE 2
Load the dataset from the hugging face repo.

"""

REPO_ID = "tomasconti/Drift_Detection"
print("Downloading native 512-D embeddings from HuggingFace")
path_train = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_train_embeddings.npy")

path_yogurt = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/yogurt_embeddings.npy")

path_test = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_test_embeddings.npy")
path_val = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_val_embeddings.npy")
path_water = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/still_water_embeddings.npy")
path_egg = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/egg_embeddings.npy")

"""
path_test="/content/grocery_test_embeddings.npy"
path_egg="/content/egg_embeddings.npy"
path_val="/content/grocery_val_embeddings.npy"
path_train="/content/grocery_train_embeddings.npy"
path_water="/content/still_water_embeddings.npy"
path_yogurt="/content/yogurt_embeddings.npy"
"""
test_embeddings = np.load(path_test)
val_embeddings = np.load(path_val)
train_embeddings = np.load(path_train)
embeddings_water = np.load(path_water)
yogurt_embeddings = np.load(path_yogurt)
egg_embeddings = np.load(path_egg)

def explore_embeddings(data, label):
    print(f"\n--- Analysis: {label} ---")
    print(f"Shape: {data.shape}")
    print(f"Mean value: {np.mean(data):.4f}")
    print(f"Standard Deviation: {np.std(data):.4f}")
    print(f"Range: [{np.min(data):.4f}, {np.max(data):.4f}]")

    # Are there any NaNs or Infinities? cloud be a problem in case
    has_nan = np.isnan(data).any()
    has_inf = np.isinf(data).any()
    print(f"Contains NaN: {has_nan} | Contains Inf: {has_inf}")

explore_embeddings(train_embeddings, "Grocery Train")
explore_embeddings(yogurt_embeddings, "Yogurt")
explore_embeddings(test_embeddings, "Grocery Test")
explore_embeddings(val_embeddings, "val ")
explore_embeddings(train_embeddings, "train")
explore_embeddings(egg_embeddings, "egg")

data = { #dictionary
    "Train": train_embeddings,
    "Val": val_embeddings,
    "Test": test_embeddings,
    "Yogurt": yogurt_embeddings,
    "Water": embeddings_water,
    "Egg": egg_embeddings
}

#for each of the set of embedding creare a hist to show up the values distributions

plt.figure(figsize=(12, 7))
for label, embeddings in data.items(): #over all the dataset of embeddings
    plt.hist(embeddings.flatten(), bins=50, alpha=0.3, label=label, density=True)

plt.legend()
plt.title("Embedding Distribution Comparison - All Datasets")
plt.xlabel("Feature Value")
plt.ylabel("Density")
plt.grid(axis='y', alpha=0.3)
plt.show()

fig, axes = plt.subplots(3, 2, figsize=(15, 12))
axes = axes.flatten()

#do not consider all the dataset but one set at time
for i, (label, embeddings) in enumerate(data.items()): #one dataset after the other
    axes[i].hist(embeddings.flatten(), bins=50, color='skyblue', alpha=0.7, density=True)
    axes[i].set_title(f"Distribution: {label}")
    axes[i].set_xlabel("Feature Value")
    axes[i].set_ylabel("Density")
    axes[i].grid(axis='y', alpha=0.3)
#axes[5].axis('off') #empty

plt.tight_layout()
plt.show()

"""### Embedding Distribution Analysis
1. Sparse Representation:
    The spike at 0 is primarily due to ReLU deactivations
2. Domain Alignment:
    The overlapping histograms confirm the model uses a
    consistent feature space Embedding differences are minimals, means the network try to extract the same features trough the model layers but some activation are differents

Now try to plot the distribution into a 2D space but also into a 3D optional space, try to see if there are some usefull pattern
"""

datasets = ["Train", "Val", "Test"] #visualize alone

combined_data = np.concatenate([data["Test"], data["Water"], data["Yogurt"], data["Egg"]]) #create big dataset combine
#creation of labels
combined_labels = ["Test"]*len(data["Test"]) + ["Water"]*len(data["Water"]) + ["Yogurt"]*len(data["Yogurt"]) +["Egg"]*len(data["Egg"])

def run_tsne(embeddings, n_dim):
    #perplexity -> check more neighbornhood, more stability | pca -> algorithm to reduce the dim
    return TSNE(n_components=n_dim, perplexity=50, random_state=42, init="pca").fit_transform(embeddings)

projs_2d = { name: run_tsne(data[name], 2) for name in datasets} # exec tsne on each dataset
projs_2d["Combined"] = run_tsne(combined_data, 2) #exec on all the dataset combine

projs_3d = {name: run_tsne(data[name], 3) for name in datasets}
projs_3d["Combined"] = run_tsne(combined_data, 3)
#################################################################################################
# 2D PLOT
fig_2d, axes_2d = plt.subplots(2, 2, figsize=(14, 12))
axes_2d = axes_2d.flatten()
#single 2d plot
for i, name in enumerate(datasets):
    axes_2d[i].scatter(projs_2d[name][:, 0], projs_2d[name][:, 1], alpha=0.6, s=20)
    axes_2d[i].set_title(f"{name} Set (2D)")
    axes_2d[i].grid(alpha=0.3)
#combine 2d plot
for label in np.unique(combined_labels):
    mask = (np.array(combined_labels) == label)
    axes_2d[3].scatter(projs_2d["Combined"][mask, 0], projs_2d["Combined"][mask, 1], label=label, alpha=0.6, s=30)
axes_2d[3].legend()
axes_2d[3].set_title("Test + Water + Yogurt (2D)")
plt.tight_layout()
plt.show()

# # OPTIONAL THE 3D PLOT
fig_3d = plt.figure(figsize=(14, 12))
for i, name in enumerate(datasets):
    ax = fig_3d.add_subplot(2, 2, i+1, projection='3d')
    ax.scatter(projs_3d[name][:, 0], projs_3d[name][:, 1], projs_3d[name][:, 2], alpha=0.6, s=20)
    ax.set_title(f"{name} Set (3D)")

ax_comb = fig_3d.add_subplot(2, 2, 4, projection='3d')
for label in np.unique(combined_labels):
    mask = (np.array(combined_labels) == label)
    ax_comb.scatter(projs_3d["Combined"][mask, 0], projs_3d["Combined"][mask, 1], projs_3d["Combined"][mask, 2], label=label, alpha=0.6, s=30)
ax_comb.legend()
ax_comb.set_title("Test + Water + Yogurt (3D Static)")
plt.tight_layout()
plt.show()

# OPTIONAL THE 3D DYNAMIC PLOT
df_3d = pd.DataFrame(projs_3d["Combined"], columns=['x', 'y', 'z'])
df_3d['Label'] = combined_labels
fig = px.scatter_3d(df_3d, x='x', y='y', z='z', color='Label', title="Test + Water + Yogurt (3D Interactive)", opacity=0.7)
fig.show()

"""### Neural Collapse principle

https://medium.com/@sharadjoshi/what-is-neural-collapse-de1decf83f48

A phenomenon occurring during the final phase of training (Terminal Phase of Training-TPT) where the network continues to optimize beyond zero training error.

This process effectively reduces noise, maximizes intra-cluster separation, and simplifies the final classification decision, ultimately leading to better generalization and adversarial robustness.

Overstepping optimization limits risks overfitting and reduced generalization.

This happens because of the logarithmic loss function, which drives the weight updates during backpropagation to create semantic clusters (one for each class).

The fact that semantically shifted images (Out-of-Distribution, or OOD) form isolated clusters in the latent space is not surprising. It is an inherent behavior of deep neural networks. Ineed, unseen features activate different, and sometimes random, sets of neurons. The consequence is the creation of distinct embeddings projected into different regions of the latent space with respect to the training domain (In-Distribution, or ID)

On the role of neurons in OOD detection (2022)
Density estimation in the latent space (ICML 2020)
Generalized OOD detection via feature space regularization (NeurIPS 2021)

The cluster visualization demonstrates the Neural Collapse phenomenon, the model's feature space exhibits within-class convergence (low variance) and between-class separation (maximized distances), effectively mapping the classes into an optimal geometric structure.

The logarithmic loss function into the CNN produce the embedding collapse into clusters.

The drifted cluster appears isolated and compact within the latent space, suggesting a distinct shift in the underlying data distribution

Execute ML clustering with train embeddings and find out the cluster head of each class distribution rappresenting the semantic anchor into the embeddings vectorial space.

Drift detection is based on euclidean distance to K=1 closest centroid of the train distribution
"""

data = { #data set of embedding
    "Train": train_embeddings,
    "Val": val_embeddings,
    "Test": test_embeddings,
    "Yogurt": yogurt_embeddings,
    "Water": embeddings_water,
    "Egg": egg_embeddings,
}

k_range = range(75, 86)
inertias = []
sil_scores = []
for k in k_range:
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42).fit(data["Train"])
    inertias.append(kmeans.inertia_)
    sil_scores.append(silhouette_score(data["Train"], kmeans.labels_))
fig, ax1 = plt.subplots(figsize=(10, 5))
color = 'tab:blue'
ax1.set_xlabel('Number of clusters (K)')
ax1.set_ylabel('Inertia', color=color)
ax1.plot(k_range, inertias, marker='o', color=color, label='Inertia')
ax1.tick_params(axis='y', labelcolor=color)
ax2 = ax1.twinx()
color = 'tab:red'
ax2.set_ylabel('Silhouette Score', color=color)
ax2.plot(k_range, sil_scores, marker='s', color=color, label='Silhouette')
ax2.tick_params(axis='y', labelcolor=color)

plt.title(" Inerzia and Silhouette (K=75 - 85)")
plt.grid(True)
plt.show()

"""With K Mean there are some difficulties with the best number of clusters"""

k_range = range(75, 86)
linkages = ['ward', 'complete', 'average', 'single']
results = []
for linkage in linkages:
    for k in k_range:
        model = AgglomerativeClustering(n_clusters=k, linkage=linkage)
        labels = model.fit_predict(data["Train"])
        score = silhouette_score(data["Train"], labels)
        results.append({"Linkage": linkage, "K": k, "Silhouette": score})
df_results = pd.DataFrame(results)
plt.figure(figsize=(12, 6))
sns.lineplot(data=df_results, x="K", y="Silhouette", hue="Linkage", marker="o")
plt.title("AgglomerativeClustering Silhouette Score between differents Linkage metrics")
plt.grid(True)
plt.show()

"""AgglomerativeClustering, with ward and average linkage, show up better clustering performance

Avoid DBSCAN because sensible to different clusters density, as in this case with rare classes.
"""

n_clusters=81
#cluster = KMeans(n_clusters=n_clusters, n_init=10, random_state=42).fit(data["Train"])
#centroids = cluster.cluster_centers_
cluster_model = AgglomerativeClustering(n_clusters=n_clusters, linkage='ward')
labels = cluster_model.fit_predict(data["Train"])
print(f"{labels[:10]}")

# Compute cluster centroids by averaging the feature vectors of all data points
# assigned to each specific cluster index (i)
# [labels == i] filter data based on cluster
centroids = np.array([data["Train"][labels == i].mean(axis=0) for i in range(n_clusters)])

K_MAX = 1  # Change this variable to set the maximum K value of KNN

#train a Kmean only on train set, can be tested also DBscan and AgglomerativeClustering!!!!!!!!!!!!!!!!!!
# DBscan -> i do not know because some algorithms have some issue with cluster that show up differents densiti into data
#kmeans = KMeans(n_clusters=81, n_init=10, random_state=42).fit(data["Train"])
#train_val_combined = np.concatenate([data["Train"], data["Val"]], axis=0)
#kmeans = KMeans(n_clusters=81, n_init=10, random_state=42).fit(train_val_combined)

# exec tsne on all all_data to allow comparison, need the same distribution reduction to all
all_data = np.concatenate([*data.values(), centroids])
all_2d = TSNE(n_components=2, perplexity=50, random_state=42, init="pca").fit_transform(all_data)
###################################################################################
#plot centroid based on trian and val
projections = {}
idx = 0
for name, emb in data.items():
    projections[name] = all_2d[idx:idx + len(emb)]
    idx += len(emb)
centroids_2d = all_2d[idx:]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for i, name in enumerate(["Train", "Val"]):
    axes[i].scatter(projections[name][:, 0], projections[name][:, 1], s=15, alpha=0.4, label=f"{name} Data")
    axes[i].scatter(centroids_2d[:, 0], centroids_2d[:, 1], marker="X", s=100, c="red", edgecolors="black", label="Centroids")
    axes[i].set_title(f"{name} Set & Centroids"); axes[i].legend()
##################################################################################

"""The validation set has been used for hyperparameter tuning and represents an accurate distribution of the domain variability.

To establish a drift threshold, I compute the interquartile range (IQR) of the distances within this set, the threshold is set to Q3​+1.5×IQR. Filtering out outliers accounting for the natural variance of the data.

Consideration:

- maybe Q3​+1.5×IQR can be a parameter
"""

knn = NearestNeighbors(n_neighbors=1, metric='euclidean').fit(centroids)
print(knn.metric)
distances = {}
for name, emb in data.items():
    d, _ = knn.kneighbors(emb)
    distances[name] = d.flatten()
val_dists = distances["Val"]
q1, q3 = np.percentile(val_dists, [25, 75])
iqr = q3 - q1
threshold = q3 + 1.5 * iqr
print(f"Threshold computed on Val set: {threshold:.3f}")

train_key = "train" if "train" in distances else "Train"
train_dists = distances[train_key]
percentiles_range = range(95, 100)
train_percentiles = np.percentile(train_dists, percentiles_range)

print("\nTrain Percentiles (90th to 99th):")
for p, val in zip(percentiles_range, train_percentiles):
    print(f"{p}th percentile: {val:.3f}")

plt.figure(figsize=(10, 6))
colors = sns.color_palette("viridis", n_colors=len(data))

for i, (label, dist) in enumerate(distances.items()):
    sns.kdeplot(dist, fill=True, alpha=0.2, color=colors[i], label=label)
    plt.axvline(np.median(dist), color=colors[i], linestyle="--", linewidth=1)
cmap = plt.get_cmap("Oranges")
for idx, (p, val) in enumerate(zip(percentiles_range, train_percentiles)):
    color = cmap(0.4 + 0.6 * (idx / len(percentiles_range)))
    lbl = f"Train P{p} = {val:.2f}" if idx in [0, len(percentiles_range) - 1] else ""
    plt.axvline(val, color=color, linestyle=":", linewidth=1.5, label=lbl)

plt.axvline(threshold, color='red', linewidth=2, label=f"Threshold = {threshold:.2f}")
plt.title("Distance to nearest centroid (K=1) – Density plot with Train Percentiles")
plt.xlabel("Euclidean distance")
plt.ylabel("Density")
plt.legend(fontsize=8, loc="upper right")
plt.grid(alpha=0.3)
plt.show()

rows = []
for name, dist_array in distances.items():
    for d in dist_array:
        rows.append({"Dataset": name, "Distance": d})
df = pd.DataFrame(rows)

plt.figure(figsize=(12, 6))
sns.boxplot(x="Dataset", y="Distance", data=df, palette="viridis", hue="Dataset")

for idx, (p, val) in enumerate(zip(percentiles_range, train_percentiles)):
    color = cmap(0.4 + 0.6 * (idx / len(percentiles_range)))
    lbl = f"Train P{p} = {val:.2f}" if idx in [0, len(percentiles_range) - 1] else ""
    plt.axhline(val, color=color, linestyle=":", linewidth=1.5, label=lbl)

plt.axhline(threshold, color='red', linestyle='--', linewidth=2, label=f"Threshold = {threshold:.2f}")
plt.title("Distance distribution (K=1) – Boxplot with Train Percentiles")
plt.legend(fontsize=8, loc="upper right")
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.3)
plt.show()

"""## Analysis

Result are very close to autoencoder approach, but in this case without gpu.

OOD data creates another Gaussian distribution of k-NN (k=1) distances. The separation of the two distributions depends on how the CNN model projects the new and drifted features

--------------------------------------------------------------------------------

This drift detection approach may struggle with samples that mirror the characteristics and distributions of the training domain.

Because of the model's generalization capabilities, it tends to project these out-of-distribution samples into the embedding space near the existing centroids, performing a 'masking' of the drifts.


-------------------------------------------------------------------------------

Egg distribution coverage box (i think) can be close to some training class, maybe to milk box of the model domain.


But the idea is still working well.

## REMEMBER, BEST EFFORT approach

I think it is not possibile execute a perfect drift detection filtering into edge 5G layer without using many computing resources.

Indeed, i prefer having a best effort and robust drift detection policy for data filtering and execute standard dirft detection into cloud.

With this drift detection filter we can reduce the cloud work.

# STAGE 3

Find out some patterns for a dynamic threshold policy
"""

from sklearn.mixture import GaussianMixture
from scipy.stats import gaussian_kde, norm
# otsu is another algorithm used in CV to detect the separation between two G. di dist, BUT, not so precise when there is a overlap
from skimage.filters import threshold_otsu

"""The distances d={d1, d2, ....dn} are manage as a mixture of two Gaussian distributions:

 >p(d)= π1 ​N(d ; μ1 ​, σ12 ​) + π2 ​N( d ; μ2 ​, σ22​)

- μi -> is the mean
- σi -> is the standard deviation
- πi -> is the mixture weight
- π1+π 2 =1.

The Gaussian density is the classical Normal probability distribution formula

Ordering μ1​<μ2​  allow to set ad first G. D. the ID and the second one OOD

Threshold set when the two G. D. are equales
> π1 ​N( x ; μ1 ​, σ12 ​) = π2 ​N( x ; μ2​ , σ22 ​)

The threshold is obtained by solving this equation above. The valid solution is the intersection point located between the two Gaussian means (μ 1<x<μ2	​).

If the two Gaussians have (approximately) equal variances (σ12≈σ22​), the quadratic equation simplifies to a linear equation.

The solution point is the intersection of the two weighted Gaussian distributions after the linear amplification assumption.

Otsu's threshold makes no Gaussian assumption. It searches over all possible thresholds and selects the one that maximizes the between-class variance (or equivalently minimizes the within-class variance) of the distances histogram.
"""

def gmm_threshold(d, percentile=0.95 ): #GaussianMixture fit with distances into a buffer and find out the point of division
    gmm=GaussianMixture(n_components=2,random_state=42).fit(d.reshape(-1,1))
    mu,sig,pi=gmm.means_.ravel(),np.sqrt(gmm.covariances_).ravel(),gmm.weights_.ravel()
    o=np.argsort(mu)
    mu1,mu2,s1,s2,p1,p2=mu[o[0]],mu[o[1]],sig[o[0]],sig[o[1]],pi[o[0]],pi[o[1]]
    ## resolution of the equation,
    a=1/(2*s1**2)-1/(2*s2**2)
    b=-mu1/s1**2+mu2/s2**2
    c=mu1**2/(2*s1**2)-mu2**2/(2*s2**2)+np.log((s1*p2)/(s2*p1))
    roots=[-c/b] if abs(a)<1e-12 and abs(b)>1e-12 else []
    if abs(a)>=1e-12:
        disc=b*b-4*a*c
        if disc>=0: roots=[(-b-np.sqrt(disc))/(2*a),(-b+np.sqrt(disc))/(2*a)]

    th=next((r for r in roots if mu1<r<mu2),None)  #distance < th  --> ID distance > th  --> OOD
    upper = norm.ppf(percentile, loc=mu1, scale=s1)
    #return th,(mu1,s1),(mu2,s2)
    return th, upper

def distances_to_centroids(X):  #Euclidean distance from each point in X to its nearest centroid.
    return knn.kneighbors(X)[0].flatten()

np.random.seed(42)   # for reproducible sampling

n_clusters = 81
train_labels = AgglomerativeClustering(n_clusters=n_clusters, linkage="ward").fit_predict(data["Train"])
centroids = np.array([ data["Train"][train_labels == i].mean(axis=0) for i in range(n_clusters) ])

ID = data["Test"]
OOD = np.concatenate([data["Water"], data["Yogurt"], data["Egg"]], axis=0)

print(f"total ID + OOD samples = {len(ID)+len(OOD)}, where ID = {len(ID)} and OOD = {len(OOD)}, OOD: W is {data["Water"].shape[0]}, E is {data["Egg"].shape[0]}, Y is {data["Yogurt"].shape[0]}")
# Distances from validation points to nearest centroid
knn = NearestNeighbors(n_neighbors=1, metric="euclidean").fit(centroids)
val_dist = knn.kneighbors(data["Val"])[0].flatten()

q1, q3 = np.percentile(val_dist, [25, 75])
safe_threshold = q3 + 1.5 * (q3 - q1) #VALIDATION – SAFE THRESHOLD (IQR)
print(f"Safe threshold: {safe_threshold:.3f}")

#test set up, (buffer dim, ID % into the buffer, OOD% into the buffer)
tests = [  (300, 95, 5), (400, 95, 5), (300, 90, 10), (400, 90, 10),(300, 99, 1), (400, 99, 1),

        #(100, 80, 20),(500, 80, 20), (500, 50, 50), (1000, 90, 10),(2000, 70, 30),
         #(300, 95, 5), (400, 10, 90), (1000, 75, 25), (1500, 60, 40), (2500, 85, 15)
          ]

fig, axes = plt.subplots(len(tests), 1, figsize=(13, 4.5 * len(tests)))

if len(tests) == 1:
    axes = [axes]

for ax, (buffer_size, id_pct, ood_pct) in zip(axes, tests):

    n_id = min( int(buffer_size * id_pct / 100), len(ID))
    n_ood = min( int(buffer_size * ood_pct / 100), len(OOD))
    print(f"n id -> {n_id}, n_ood-> {n_ood}" )
    X_sample = np.concatenate([ ID[np.random.choice(len(ID), n_id, replace=False)], OOD[np.random.choice(len(OOD), n_ood, replace=False)] ])
    labels = np.concatenate([np.repeat("ID", n_id), np.repeat("OOD", n_ood)])
    shuffled_indices = np.random.permutation( len(X_sample) ) # shuffle keeping the correspondences

    X_sample = X_sample[shuffled_indices]
    labels = labels[shuffled_indices]

    dist = distances_to_centroids(X_sample)
    id_dist = dist[ labels == "ID" ]

    gmm_val, upper = gmm_threshold(dist, 0.95)


    otsu_val = threshold_otsu(dist)
    id_mean = np.mean(id_dist)
    id_median = np.median(id_dist)
    #id_p95 = np.percentile(id_dist, 95)
    id_p95 = np.percentile( np.unique(id_dist) , 95)
    x_vals = np.linspace(dist.min(), dist.max(), 400)


    for cls, color in [("ID", "royalblue"), ("OOD", "crimson")]:
        d = dist[labels == cls]
        bins = np.linspace(dist.min(), dist.max(), 41)
        ax.hist(d, bins=bins, density=True, alpha=0.5, color=color, label=f"{cls} hist")
        if len(d) > 1:
            ax.plot(x_vals, gaussian_kde(d)(x_vals), color=color, lw=2, label=f"{cls} KDE")


    lines = [ (gmm_val, "orange", "--", 2, f"GMM={gmm_val:.3f}"),(upper, "magenta", "--", 2, f"GMM p95={upper:.3f}"), (otsu_val, "purple", ":", 2, f"Otsu={otsu_val:.3f}"), (safe_threshold, "green", "-.", 2, f"Safe={safe_threshold:.3f}"),
        (id_mean, "cyan", "-", 2, f"ID mean={id_mean:.3f}"), (id_median, "blue", "-", 2, f"ID median={id_median:.3f}"), (id_p95, "black", ":", 2, f"ID p95={id_p95:.3f}"),
        (safe_threshold, "red", "-", 4, f"SAFE={safe_threshold:.3f}"), ]

    for val, color, linestyle, linewidth, label in lines:
        ax.axvline(val, color=color, linestyle=linestyle, linewidth=linewidth, label=label)

    ax.axvspan(safe_threshold, dist.max(), color="red", alpha=0.08)
    print(f"ID: {len(dist[labels=='ID'])}, OOD: {len(dist[labels=='OOD'])}")
    ax.set_title(f"Buffer={len(X_sample)} | ID={id_pct}% OOD={ood_pct}%")
    ax.set_xlabel("Distance to nearest train centroid")
    ax.set_ylabel("Density")
    ax.legend(fontsize=8, loc="upper right")
    ax.grid(alpha=0.35)

plt.tight_layout()
plt.show()

"""While a SAFE threshold based on the validation set distribution is a valid approach for a static filtering policy, a more dynamic solution might be required for better adaptability. When the percentage of Out-of-Distribution (OOD) samples is low, it becomes difficult to filter OOD data with high precision without misclassify In-Distribution (ID) samples. Buffer dimensioning is critical because with a small sample size, it is statistically challenging to accurately distinguish between the two distributions. GaussianMixture.fit() is not ideal for a hard-real-time operation. However, implementing a sample batch policy could optimize its performance for streaming or real-time environments

# New consideration about the distance distribution

The most interesting OOD ratio falls within the 1% to 5% range. For this reason, assuming a two-Gaussian distance distribution is incorrect for this use case. Since this range is our primary focus, I will need to change the general approach.

Now, there is only a single Gaussian distribution composed of ID distances, with a few OOD outliers located in the tail. This scenario is not well-suited for a two-Gaussian fit. Consequently, I have decided to change my policy and use a dynamic percentile upper bound to filter out the OOD samples.

# STAGE 4

I am looking for a dynamic GMM thresholding method that adjusts threshold around a 'SAFE' value

## RealTimeOODDetector class

Perform soft real-time Out-of-Distribution (OOD) detection. Use an adaptive threshold to determine whether incoming data is  closer to a known In-Distribution (ID) data or new OOD data.

Dynamically computes the threshold based on historical distance distributions.

The threshold is derived into two distinct Gaussian distance distributions:

  - One representing In-Distribution (ID) data.
  - One representing Out-of-Distribution (OOD) data.

The proposed system can be considered a soft real-time solution. It does not guarantee hard real-time constraints because the periodic gmm.fit() operation introduces latency spikes that may exceed the hard real time deadline.

 Increasing the batch size reduces the number of threshold updates reducing the threshold relaibility, but also improves the overall real-time performance and bringing the system closer to hard real-time behavior

## NEW RealTimeOODDetector class

The core concept relies on evaluating the upper tail of the ID  distance distribution using percentiles to identify real-time OOD drifts.

This solution manages a random data stream with a low percentage of OOD samples.

It uses a sliding window of distances to calculate the percentile per batch, reducing the impact of noise.

Adjusting the percentile configuration sets the filter's sensitivity. Higher values improve precision and restrict traffic, but compromise accuracy by letting OOD samples been blocked.

While shrinking the window and batch sizes makes the threshold more adaptable, it also increases general noise.
"""

"""
REPO_ID = "tomasconti/Drift_Detection"
print("Downloading native 512-D embeddings from HuggingFace")
path_train = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_train_embeddings.npy")
path_yogurt = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/yogurt_embeddings.npy")
path_test = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_test_embeddings.npy")
path_val = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/grocery_val_embeddings.npy")
path_water = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/still_water_embeddings.npy")
path_egg = hf_hub_download(repo_id=REPO_ID, filename="good_to_delivery/egg_embeddings.npy")
"""
from scipy.linalg import pinv
from scipy.linalg import sqrtm
## NEW MODEL 68C, 98% on train - 96% on val and 92% on test
#path_test="/content/drive/MyDrive/embeddings_68C/test_dataset_embedding_distribution__68C.npy"

path_test_correct="/content/drive/MyDrive/embeddings_68C/correct_test_embeddings.npy"
path_test_wrong="/content/drive/MyDrive/embeddings_68C/correct_test_embeddings.npy"

path_egg="/content/drive/MyDrive/embeddings_68C/eags_drift_embedding_distribution__68C.npy"
path_val="/content/drive/MyDrive/embeddings_68C/validation_dataset_embedding_distribution__68C.npy"
path_train="/content/drive/MyDrive/embeddings_68C/train_dataset_embedding_distribution_68C.npy"
path_water="/content/drive/MyDrive/embeddings_68C/water_drift_embedding_distribution__68C.npy"
path_yogurt="/content/drive/MyDrive/embeddings_68C/yogurt_drift_embedding_distribution__68C.npy"

#test_embeddings = np.load(path_test)
test_embeddings_correct = np.load(path_test)
test_embeddings_wrong = np.load(path_test)

# 0 = correct ID  and 1 = wrong ID
test_labels_type = np.concatenate([ np.zeros(len(test_embeddings_correct), dtype=int),np.ones(len(test_embeddings_wrong), dtype=int)])
test_embeddings = np.concatenate([test_embeddings_correct, test_embeddings_wrong], axis=0)

print(f" Test labels: {test_labels_type.shape[0]}")
print(f"Test total: {test_embeddings.shape}")
print(f"Test wrong: {test_embeddings_wrong.shape}")
print(f"Test right: {test_embeddings_correct.shape}")
#test_embeddings = np.load(path_test)

val_embeddings = np.load(path_val)
train_embeddings = np.load(path_train)
embeddings_water = np.load(path_water)
yogurt_embeddings = np.load(path_yogurt)
egg_embeddings = np.load(path_egg)

print("Embeddings shapes:")
print(f"Train: {train_embeddings.shape}")
print(f"Val:   {val_embeddings.shape}")
print(f"Test:  {test_embeddings.shape}")
print(f"Water: {embeddings_water.shape}")
print(f"Yogurt:{yogurt_embeddings.shape}")
print(f"Egg:   {egg_embeddings.shape}")
# re create the dataset and re execute all the setup code
data = { "Train": train_embeddings, "Val": val_embeddings,
        "Test": test_embeddings, "Test_type": test_labels_type, # add the id type into the dataset
         "Yogurt": yogurt_embeddings,
         "Water": embeddings_water, "Egg": egg_embeddings }
##################################################################################################################################################

cov_matrix = np.cov(train_embeddings, rowvar=False)
inv_cov_matrix = np.linalg.pinv(cov_matrix)

##################################################################################################################################################
n_clusters = 68 ######################################### SUPER IMPORTANT
cluster_model = AgglomerativeClustering(n_clusters=n_clusters, linkage='ward')
labels = cluster_model.fit_predict(data["Train"])
centroids = np.array( [data["Train"][labels == i].mean(axis=0) for i in range(n_clusters)] )
#knn_val = NearestNeighbors(n_neighbors=1, metric='euclidean').fit(centroids) #######################IS THIS RIGHT ??????????????????????????????
##################################################################################################################################################
knn = NearestNeighbors(n_neighbors=1, metric="euclidean").fit(centroids)
def mahalanobis_to_nearest_centroid(embeddings):
    _, idx = knn.kneighbors(embeddings)
    nearest = centroids[idx.ravel()]
    diff = embeddings - nearest
    return np.sqrt(np.sum((diff @ inv_cov_matrix) * diff, axis=1)) #Mahalanobis to the closet train centroid

train_dists = mahalanobis_to_nearest_centroid(train_embeddings)
val_dists = mahalanobis_to_nearest_centroid(val_embeddings)
test_dists = mahalanobis_to_nearest_centroid(test_embeddings)
water_dists = mahalanobis_to_nearest_centroid(embeddings_water)
yogurt_dists = mahalanobis_to_nearest_centroid(yogurt_embeddings)
egg_dists = mahalanobis_to_nearest_centroid(egg_embeddings)
# validation does not contains already seen ID data, making the threshold more representative to the reality
threshold = np.percentile(val_dists, 98)
print(f"Threshold = {threshold:.2f}")
##################################################################################################################################################
#val_dists, _ = knn_val.kneighbors(data["Val"])
#val_dists = val_dists.flatten()
#q1, q3 = np.percentile(val_dists, [25, 75])
#iqr = q3 - q1
#initial_threshold = q3 + 1.5 * iqr # base the starting and safe threshold on validation set because representative of the domain but only used for hyperparameter tuning and not for weights
#train_dists, _ = knn_val.kneighbors(data["Train"])
#train_dists, _ = knn.kneighbors(train_m)
#train_dists = train_dists.flatten()
#initial_threshold = np.percentile(train_dists, 99)
#print(f"\nIQR starting threshold : {initial_threshold:.3f}\n")
#TOTAL_SAMPLES=2400
TOTAL_SAMPLES = egg_embeddings.shape[0]+yogurt_embeddings.shape[0]+embeddings_water.shape[0]+test_embeddings.shape[0]
print(f"TOTAL_SAMPLES {TOTAL_SAMPLES}")
for name, dists in {  "Train": train_dists, "Val": val_dists, "Test": test_dists, "Water": water_dists, "Yogurt": yogurt_dists, "Egg": egg_dists, }.items():
    print(f"{name:8s}: {(dists > threshold).mean()*100:6.2f}% above threshold")

sns.kdeplot(train_dists,label="Train")
sns.kdeplot(val_dists,label="Val")
sns.kdeplot(test_dists,label="Test")
plt.axvline(np.percentile(val_dists,95),color="red")
plt.axvline(np.percentile(val_dists,97),color="red")
plt.axvline(np.percentile(val_dists,99),color="green")
plt.legend()

class RealTimeOODDetector:
    def __init__( self,  centroids,  window_size=400,  batch_size=40,  initial_threshold=None,  smoothing=0.9,  min_samples=50,
                 percentile=90,  max_percentile=95,  safe_threshold=None,  max_consecutive_drops=5, max_consecutive_ups=5,
                  median_window=5, history_buffer_size=20 , smooth_safety_th=False, inv_cov_matrix=None):
        # idk if use distance_buffer or batch_distances for percentile operation
        self.knn = NearestNeighbors(n_neighbors=1, metric="euclidean")
        self.knn.fit(centroids)
        self.centroids = centroids
        self.distance_buffer = deque(maxlen=window_size)
        #self.batch_distances = []   # if we don't use this batch_distances for percentile operation it can be replace with a counter
        self.batch_distances = 0
        self.threshold = initial_threshold
        self.safe_threshold = safe_threshold
        self.batch_size = batch_size
        self.smoothing = smoothing
        self.min_samples = min_samples
        self.percentile = percentile
        self.max_percentile = max_percentile
        self.max_consecutive_drops = max_consecutive_drops
        self.max_consecutive_ups = max_consecutive_ups
        self.consecutive_drops = 0
        self.consecutive_ups = 0
        self.median_window = median_window
        self.batch_percentiles = deque(maxlen=median_window)
        self.smooth_safety_th = smooth_safety_th
        self.inv_cov_matrix = inv_cov_matrix
        if inv_cov_matrix is None:
          raise ValueError("Incompatible parameters: this system require the inv_cov_matrix of the test set ")
        if safe_threshold is None and smooth_safety_th is True:
            raise ValueError("Incompatible parameters: smooth_safety_th cannot be True if safe_threshold is None")
        self.threshold_flow = deque(maxlen=max(max_consecutive_drops, max_consecutive_ups)+1)
        self.threshold_trend = []

        self.fp_correct = 0  # correct ID and classify as OOD
        self.fp_wrong = 0    # wrong ID and classify as OOD

        self.counter = 0
        self.history = {   "time": [],   "distances": [],    "thresholds": [],     "predictions": [],   "ground_truth": [],   "trend": []  }

    def _compute_raw_threshold(self, distances):
        if len(distances) < self.min_samples:
            return None
        #return np.percentile(np.unique(distances), self.percentile)
        #return np.percentile(distances, self.percentile) # real time operation
        #return np.percentile(np.unique(self.distance_buffer), self.percentile) # delete duplicates before percentile, equals weights IDK
        return np.percentile(self.distance_buffer, self.percentile)

    def _fallback_threshold(self, distances): #fall back policy
        median = np.median(distances)
        mad = np.median(np.abs(distances - median))
        return median + 2.0 * mad

    def _update_threshold(self):
        if len(self.distance_buffer) < self.min_samples:
            return
        buffer = np.asarray(self.distance_buffer)
        thr = self._compute_raw_threshold(buffer) #calculate the th percentile
        if thr is None:
            thr = self._fallback_threshold(buffer)
        self.batch_percentiles.append(thr) #history of th
        if len(self.batch_percentiles) >= 2:
            thr_median = np.median(self.batch_percentiles) #cloud be helpful in case of the outliers/spike
        else:
            thr_median = thr
        thr_candidate = min(thr_median, np.percentile(buffer, self.max_percentile)) # another security check con the th values
        if self.threshold is None:
            new_thr = thr_candidate
            trend = "INIT"
        else:
            if thr_candidate > self.threshold:
                self.consecutive_ups += 1 #update ups
                self.consecutive_drops = 0 #resent drops
                trend = "UP"
            elif thr_candidate < self.threshold:
                self.consecutive_drops += 1 #update drops
                self.consecutive_ups = 0 #reset ups
                trend = "DOWN"
            else: #reset all because it is stable
                self.consecutive_ups = 0
                self.consecutive_drops = 0
                trend = "SAME"

            smoothing_target = thr_candidate
            is_reset = False

            if self.safe_threshold is not None and (self.consecutive_drops >= self.max_consecutive_drops or self.consecutive_ups >= self.max_consecutive_ups): # case with self.safe_threshold
                smoothing_target = self.safe_threshold
                trend = "RESET_SAFE"
                self.consecutive_drops = 0
                self.consecutive_ups = 0
                if not self.smooth_safety_th: #if there is no smooth_safety_th execute a hard cut of the th value, if it is not the smoothing_target will be smoothed
                    is_reset=True

            elif self.consecutive_drops >= self.max_consecutive_drops and self.safe_threshold is None:
                back_index = self.consecutive_drops + 1
                if len(self.threshold_flow) >= back_index:
                    smoothing_target = self.threshold_flow[-back_index] #back track
                    trend = "RESET_DOWN"
                else:
                    trend = "SAME"
                self.consecutive_drops = 0
                self.consecutive_ups = 0

            elif self.consecutive_ups >= self.max_consecutive_ups and self.safe_threshold is None:
                back_index = self.consecutive_ups + 1
                if len(self.threshold_flow) >= back_index:
                    smoothing_target = self.threshold_flow[-back_index] #back track
                    trend = "RESET_UP"
                else:
                    trend = "SAME"
                self.consecutive_ups = 0
                self.consecutive_drops = 0

            if is_reset:
              new_thr = smoothing_target
            else:
              #threshold_t = 0.99 * threshold_t + 0.01 * new_threshold an alternative can be let the th flow along the safty value
              new_thr = self.smoothing * self.threshold + (1 - self.smoothing) * smoothing_target #allways

        self.threshold = new_thr # the current th value became the old one
        #self.threshold_flow.append(new_thr) #history of the past th values for backtrack
        self.threshold_flow.append(thr_candidate) # BETTER !!!!!!
        self.threshold_trend.append(trend)

    #def process(self, embedding, true_label=None):
    def process(self, embedding, true_label=None, is_correct=None):
        #dist = self.knn.kneighbors(np.asarray(embedding).reshape(1, -1))[0][0][0] #distance inference
        emb = np.asarray(embedding).reshape(1, -1)
        idx = self.knn.kneighbors(emb, return_distance=False)[0][0] #closest centroid
        nearest_centroid = self.centroids[idx]
        diff = emb.ravel() - nearest_centroid
        dist = float( np.sqrt(diff @ self.inv_cov_matrix @ diff.T))

        self.distance_buffer.append(dist) #update hisotry distance buffer
        #self.batch_distances.append(dist)
        self.batch_distances+=1
        self.counter += 1

        #if len(self.batch_distances) >= self.batch_size:
        if self.batch_distances >= self.batch_size:
            #self.batch_distances.clear()
            self.batch_distances = 0
            self._update_threshold() #after a batch of distance update the th

        if self.threshold is None and len(self.distance_buffer) >= self.min_samples: #end up of the warm up
            buffer = np.asarray(self.distance_buffer)
            thr = self._compute_raw_threshold(buffer)
            if thr is None:
                thr = self._fallback_threshold(buffer)
            self.threshold = min(thr, np.percentile(buffer, self.max_percentile)) # now threshold is not more None

        is_ood = self.threshold is not None and dist > self.threshold # classification operation

        trend = self.threshold_trend[-1] if self.threshold_trend else "INIT"

        self.history["time"].append(self.counter - 1)
        self.history["distances"].append(dist)
        self.history["thresholds"].append(self.threshold if self.threshold is not None else np.nan)
        self.history["predictions"].append(int(is_ood))
        self.history["ground_truth"].append(0 if true_label is None else true_label)
        self.history["trend"].append(trend)

        if true_label == 0 and is_ood:  # false positive
          if is_correct == True or is_correct == 1:  # right ID
            self.fp_correct += 1
          elif is_correct == False or is_correct == 0:  # wrong ID
            self.fp_wrong += 1

        return dist, is_ood, self.threshold

"""Now there are three main modalities for the threshold policy:

- Without Safety Threshold: The threshold adjusts freely. In case of extrema fluttuation the system resets it to its historical position, specifically the value it held immediately before the breach occurred.

- With Safety Threshold: Applies a strict, predefined safe threshold (hard cut) as soon as there is a extrema fluctuation.

- Hybrid Modality: The threshold follows a standard smoothing. However, if a extrema fluctuation occurs, it smoothly transitions to the safe_threshold instead of using an instant hard cut.

The Gaussian.fit real time issue has been resolved
"""

"""
def generate_random_stream(data, n_test, n_ood, replace=False): #ID and/or OOD are stream noise into the incoming signal
    test_embs = data["Test"] # ID → data["Test"]
    ood_embs = np.concatenate( [data["Water"], data["Yogurt"], data["Egg"]] ) # OOD → Water, Yogurt, Egg
    # security
    n_test = min(n_test, len(test_embs))
    n_ood = min(n_ood, len(ood_embs))
    # random sampling with or with out replacement
    sampled_test = test_embs[   np.random.choice(len(test_embs), n_test, replace=replace)   ]
    sampled_ood = ood_embs[   np.random.choice(len(ood_embs), n_ood, replace=replace)  ]
    combined = np.concatenate(  [sampled_test, sampled_ood]  )
    labels = np.concatenate(   [np.zeros(n_test, dtype=int),  np.ones(n_ood, dtype=int)]   ) #labels 0 = ID 1 = OOD
    perm = np.random.permutation( len(combined) ) # random shuffle, creare a stream signal with noise inside
    return combined[perm], labels[perm]
"""
"""
def generate_worst_case_stream(data, centroids, n_test, n_ood):
    knn = NearestNeighbors(n_neighbors=1, metric="euclidean").fit(centroids)
    ood_pool = np.vstack([data["Yogurt"], data["Water"], data["Egg"]])
    dists, _ = knn.kneighbors(ood_pool)
    sorted_indices = np.argsort(dists.flatten())
    hard_ood = ood_pool[sorted_indices[:n_ood]]# is a sample is very close to a centroid it is a worst case
    id_indices = np.random.choice(len(data["Test"]), size=n_test, replace=True)
    id_samples = data["Test"][id_indices]
    X = np.vstack([id_samples, hard_ood])
    y = np.array([0] * n_test + [1] * n_ood) # label = for the ID and 1 for OOD
    perm = np.random.permutation(len(y)) #shuffling
    return X[perm], y[perm]
"""
def generate_random_stream(data, n_test, n_ood, replace=False):
    test_embs = data["Test"]
    ood_embs = np.concatenate([data["Water"], data["Yogurt"], data["Egg"]])

    # Campionamento ID - gestisci replace
    if not replace and n_test > len(test_embs):
        print(f"  → Using replace=True for ID (n_test={n_test}, pool={len(test_embs)})")
        test_idx = np.random.choice(len(test_embs), n_test, replace=True)
    else:
        test_idx = np.random.choice(len(test_embs), n_test, replace=replace)

    sampled_test = test_embs[test_idx]
    sampled_test_type = data["Test_type"][test_idx]


    if not replace and n_ood > len(ood_embs):
        print(f"  → Using replace=True for OOD (n_ood={n_ood}, pool={len(ood_embs)})")
        sampled_ood = ood_embs[np.random.choice(len(ood_embs), n_ood, replace=True)]
    else:
        sampled_ood = ood_embs[np.random.choice(len(ood_embs), n_ood, replace=replace)]

    X = np.concatenate([sampled_test, sampled_ood])
    y_detector = np.concatenate([np.zeros(n_test), np.ones(n_ood)])
    y_type = np.concatenate([sampled_test_type, np.full(n_ood, 2)])
    perm = np.random.permutation(len(X))

    return X[perm], y_detector[perm], y_type[perm]

def generate_worst_case_stream(data, centroids, n_test, n_ood):
    knn = NearestNeighbors(n_neighbors=1, metric="euclidean").fit(centroids)
    ood_pool = np.vstack([data["Yogurt"], data["Water"], data["Egg"]])


    if n_ood > len(ood_pool):
        print(f"  → Using replacement for worst-case OOD (n_ood={n_ood}, pool={len(ood_pool)})")
        indices = np.random.choice(len(ood_pool), n_ood, replace=True)
        hard_ood = ood_pool[indices]
    else:
        dists, _ = knn.kneighbors(ood_pool)
        sorted_indices = np.argsort(dists.flatten())
        hard_ood = ood_pool[sorted_indices[:n_ood]]


    test_embs = data["Test"]
    if n_test > len(test_embs):
        print(f"  → Using replacement for ID (n_test={n_test}, pool={len(test_embs)})")
        id_indices = np.random.choice(len(test_embs), size=n_test, replace=True)
    else:
        id_indices = np.random.choice(len(test_embs), size=n_test, replace=False)

    id_samples = test_embs[id_indices]
    id_type = data["Test_type"][id_indices]

    X = np.vstack([id_samples, hard_ood])
    y_detector = np.concatenate([np.zeros(n_test, dtype=int), np.ones(n_ood, dtype=int)])
    y_type = np.concatenate([id_type, np.full(n_ood, 2, dtype=int)])
    perm = np.random.permutation(len(y_detector))

    return X[perm], y_detector[perm], y_type[perm]

"""## System performance stress-test

A testing phase to evaluate the overall performance of the system using two distinct stream-based workflows:

* **Randomly Sampled Streams:** Data streams composed of a random mix of ID and OOD data, evaluated across varying percentage ratios.
* **Wave-Based Streams:** Data streams structured in sequential "waves" of ID and/or OOD data, also tested using different percentage distributions.

Plot the confusion matrix and distance metrix evolution with the threshold for each test
"""

from sklearn.metrics import auc, precision_recall_curve, roc_curve

def plot_confusion_matrix(y_true, y_pred, title, ax, fp_correct, fp_wrong):
    #ConfusionMatrixDisplay.from_predictions(y_true, y_pred, ax=ax, cmap='Blues')
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(ax=ax, cmap='Blues')

    total=cm.sum() # all data sample managed
    OOD_predicted=cm[:,1].sum() #all the item in the row with label 1 = OOD
    traffic_blocked = 100 - ( (OOD_predicted/total) *100)
    traffic_allowed = (OOD_predicted/total)*100
    total_fp = fp_correct + fp_wrong
    if total_fp > 0:
      fp_correct_pct = (fp_correct / total_fp) * 100
      fp_wrong_pct = (fp_wrong / total_fp) * 100
      print(f"  corrent ID into false positives: {fp_correct} ({fp_correct_pct:.1f}%)")
      print(f"  wrong ID into false positives:   {fp_wrong} ({fp_wrong_pct:.1f}%)")
      print(f"  Corrent/Wrong false positive ID ratio: {fp_wrong/fp_correct if fp_correct > 0 else float('inf'):.2f}")
    ax.set_title(title)
    print(f"\n OOD_predicted--> {OOD_predicted} \n traffic_allowed: {traffic_allowed:.2f} ----- {traffic_blocked:.2f}")

    return traffic_allowed, traffic_blocked


def plot_temporal(time, dist, thresh, pred, true, title, ax1, ax2, ax3):

    ax1.plot(time, dist, 'b.', alpha=0.3, label='Distance')
    ax1.plot(time, thresh, 'r-', lw=2, label='Threshold')
    anom_idx = np.where(pred == 1)[0]
    if len(anom_idx) > 0:
        ax1.scatter(anom_idx, dist[anom_idx], color='red', s=50, marker='^', label='OOD detected')
    true_idx = np.where(true == 1)[0]
    if len(true_idx) > 0:
        ax1.scatter(true_idx, dist[true_idx], color='green', s=30, marker='o', facecolors='none', label='Ground truth OOD')

    ax1.legend()
    ax1.set_title(title)
    ax1.set_ylabel('Distance')
    ax1.grid(alpha=0.3)

    ax2.plot(time, thresh, 'g-', lw=2)
    ax2.set_ylabel('Threshold')
    ax2.grid(alpha=0.3)

    ax3.plot(time, dist, 'b-', alpha=0.6, label='Distance')
    ax3.plot(time, thresh, 'r--', label='Threshold')
    ax3.set_xlabel('Time (samples)')
    ax3.set_ylabel('Distance')
    ax3.legend()
    ax3.grid(alpha=0.3)

#  y_true : array-like Ground-truth labels         0-> ID    1 -> OOD
#  y_scores : array-like OOD scores produced by the model. In this implementation the score is the distance from the nearest ID centroid. Larger distances indicate a higher likelihood that a sample is OOD.
def compute_auprc_and_fpr95(y_true, y_scores):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    """
    small recap recall=TP/(TP+FN) ->  how many OOD the system can detect over the possible amout of OOD
    precision=TP/(TP+FP) -> how often the detector that predict OOD have right
    what realy change bases on the data stream are the distances distributions
    The Precision-Recall curve is obtained by varying the decision threshold over the predicted OOD scores (centroid distances). For each threshold, Precision and Recall are computed.
    AUPRC (Area Under the Precision-Recall Curve) summarizes the detector's performance across all possible thresholds. A high AUPRC indicates that
    the centroid-distance score is effective at distinguishing OOD samples from ID samples while maintaining high precision as recall increases.
    """
    prec, rec, _ = precision_recall_curve(y_true, y_scores)
    # auprc_val is the area, if it is higher means that centroid distance as score to detect OOD is good
    auprc_val = auc(
        rec, prec
    )  # higher is better, it is the area under the precision and recall curve
    ax1.plot(rec, prec, color="b", lw=2, label=f"AUPRC = {auprc_val:.4f}")
    ax1.fill_between(rec, prec, alpha=0.2, color="b")
    ax1.set_title(
        "Precision-Recall Curve (OOD)", fontsize=12, fontweight="bold"
    )
    ax1.set_xlabel("Recall (TPR)")
    ax1.set_ylabel("Precision")
    ax1.set_xlim([0.0, 1.0])
    ax1.set_ylim([0.0, 1.05])
    ax1.grid(True, linestyle="--", alpha=0.6)
    ax1.legend(loc="lower left")
    ax2.axhline(
        y=0.95,
        color="red",
        linestyle=":",
        linewidth=1.5,
        label="Target TPR (95%)",
    )
    ############################################################################################################################################################################################################################
    """
    FPR@95TPR is a standard OOD detection metric. It measures the False Positive Rate when the detector achieves at least a 95% True Positive Rate (Recall).
    In other words, once the detector is configured to correctly identify 95% of all OOD samples, FPR@95TPR tells us what fraction of ID samples are mistakenly flagged as OOD.
    Lower values indicate a better detector because fewer ID samples are  incorrectly rejected while maintaining a very high OOD detection rate.
    """
    fpr, tpr, _ = roc_curve(y_true, y_scores, pos_label=1)  #
    # Threshold that allows the detector to correctly identify at least 5% of the OOD samples.
    idx = np.where(tpr >= 0.95)[0]
    if len(idx) > 0:
        fpr_95 = fpr[idx[0]]  # lower is better
    else:
        fpr_95 = 1.0  # fall back
    ax2.plot(fpr, tpr, color="darkorange", lw=2, label="Curva ROC")
    ax2.plot([0, 1], [0, 1], color="navy", lw=1, linestyle="--", label="Random")
    if len(idx) > 0:
        ax2.plot(
            fpr_95,
            0.95,
            "ro",
            markersize=8,
            label=f"FPR@95 = {fpr_95:.4f}",
        )
        ax2.vlines(
            x=fpr_95,
            ymin=0,
            ymax=0.95,
            colors="red",
            linestyles=":",
            linewidth=1.5,
        )
    ax2.set_title("ROC Curve & FPR@95", fontsize=12, fontweight="bold")
    ax2.set_xlabel("False Positive Rate (FPR)")
    ax2.set_ylabel("True Positive Rate (TPR / Recall)")
    ax2.set_xlim([0.0, 1.0])
    ax2.set_ylim([0.0, 1.05])
    ax2.grid(True, linestyle="--", alpha=0.6)
    ax2.legend(loc="lower right")
    plt.tight_layout()
    plt.show()
    return float(auprc_val), float(fpr_95)

#def start_test_phase(stream_data, stream_labels, detector_params, nome_test, val_dists, warm_up_limit): # labels 0 = ID 1 = OOD
def start_test_phase(stream_data,stream_labels,stream_quality,detector_params,nome_test,val_dists,warm_up_limit):
    if isinstance( stream_labels[0], (str, np.str_)): #labels chack
        print(f"\n string labels input, convert to int data type")
        stream_labels = np.array(    [ 0 if lab == 'Test' else 1 for lab in stream_labels ]  )
    else:
        print(f"\n all int data types")
        stream_labels = np.array(stream_labels, dtype=int)
    stream_quality = np.array(stream_quality, dtype=int)
    detector =RealTimeOODDetector(**detector_params)
    # Warm-up fill buffer with validation set sample
    #for d in val_dists[:300]:
    for d in val_dists[:warm_up_limit]:
        detector.distance_buffer.append(d)
    """
    for emb, lab in zip(stream_data, stream_labels): # creation of the embedding data stream
        #labels 0 = ID 1 = OOD
        detector.process(emb, true_label= int(lab) ) #detector receives embedding and true label 0-1 of the sample
    """
    for emb, lab, qual in zip(stream_data, stream_labels, stream_quality):
      if lab == 0:  # ID
        is_correct = (qual == 0)  # True se corretto (qual=0), False se errato (qual=1)
      elif lab == 1:  # OOD
        is_correct = None
      else:
        print(f"ERROR: label {lab} non riconosciuta!")
        is_correct = None

      detector.process(emb, true_label=int(lab), is_correct=is_correct)
      #detector.process(  emb,  true_label=int(lab) )
    #if len(detector.batch_distances) > 0:
     #  detector._update_threshold()
    #plot the result of the stream that get in to the detector
    if detector.batch_distances>0:
      detector._update_threshold()
    ########################################################################
    hist = detector.history
    time_steps = np.array(hist['time'])
    distances = np.array(hist['distances'])
    thresholds = np.array(hist['thresholds'])
    predictions = np.array(hist['predictions'])
    ground_truth = np.array(hist['ground_truth'])
    ########################################################################
    trend = np.array(hist['trend'])
    reset_down_count = (trend == "RESET_DOWN").sum()
    reset_up_count = (trend == "RESET_UP").sum()
    reset_same_count = (trend == "SAME").sum()
    reset_safe_count = (trend == "RESET_SAFE").sum()
    print(f"RESET_DOWN count: {reset_down_count}")
    print(f"RESET_UP count: {reset_up_count}")
    print(f"SAME count: {reset_same_count}")
    print(f"RESET_SAFE count: {reset_safe_count}")
    ########################################################################
    time_steps = time_steps[warm_up_limit:]
    distances = distances[warm_up_limit:]
    thresholds = thresholds[warm_up_limit:]
    predictions = predictions[warm_up_limit:]
    ground_truth = ground_truth[warm_up_limit:]
    ########################################################################
    valid = ~np.isnan(thresholds) # cleaning mask
    #######################################################################
    time_valid = time_steps[valid]
    dist_valid = distances[valid]
    th_valid = thresholds[valid]
    pred_valid = predictions[valid]
    true_valid = ground_truth[valid].astype(int)
    ######################################################################
    auprc_val, fpr95_val = compute_auprc_and_fpr95(true_valid, dist_valid) #based on the random data traffic define for each sample the detected distance from the closes centroids
    ######################################################################
    if np.sum(pred_valid) == 0:
        print("\n ERROR: there was no OOD!")
        acc = accuracy_score(true_valid, pred_valid)
        prec = rec = f1 = 0.0
    else:
        acc = accuracy_score(true_valid, pred_valid) #sample with a correctly prediction
        #pos_label=1 ----> OOD class
        prec = precision_score(true_valid, pred_valid, pos_label=1, zero_division=0) #how often the detector that predict OOD have right
        rec = recall_score(true_valid, pred_valid, pos_label=1, zero_division=0) #how many OOD the system can detect
        f1 = f1_score(true_valid, pred_valid, pos_label=1, zero_division=0) #armonic mean between accuracy and precision

    print("\n" + "="*60)
    print(f" TEST: {nome_test}")
    print("="*60)
    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f}")
    print(f"AUPRC: {auprc_val:.4f} | FPR@95: {fpr95_val*100:.2f}%")

    #print(classification_report(true_valid, pred_valid, labels=[0, 1], target_names=['ID', 'OOD'], zero_division=0))
    classification_report(true_valid, pred_valid, labels=[0, 1], target_names=['ID', 'OOD'], zero_division=0)
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 12), sharex=True)
    plot_temporal(time_valid, dist_valid, th_valid, pred_valid, true_valid, f"{nome_test} - Acc={acc:.3f}, F1={f1:.3f}", ax1, ax2, ax3)
    plt.tight_layout()
    plt.show()

    fig2, ax = plt.subplots(figsize=(6, 5))
    traffic_allowed, traffic_blocked=plot_confusion_matrix(true_valid, pred_valid, f" confusion matrix - {nome_test}", ax, detector.fp_correct, detector.fp_wrong )

    plt.tight_layout()
    plt.show()

    #return {'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1,  'TB': traffic_blocked, 'TA': traffic_allowed}
    return { 'acc': acc,  'prec': prec,  'rec': rec, 'f1': f1,  'TB': traffic_blocked, 'TA': traffic_allowed,'auprc': auprc_val, 'fpr95': fpr95_val }

"""
detector_params = { # detector parameters
    "centroids": centroids,
    "window_size": 50,
    "batch_size": 5,
    "initial_threshold": initial_threshold,
    "percentile":99,
    "smoothing": 0.90,
    "min_samples":50,
    "max_percentile": 99,
    "safe_threshold": initial_threshold,
    "max_consecutive_drops":5,
    "max_consecutive_ups": 5,
    "median_window":3,
    "smooth_safety_th":True
}
"""
detector_params = {
    "centroids": centroids,
    "inv_cov_matrix": inv_cov_matrix, # important addition information that help the simple eucledian distance
    "window_size": 50,
    "batch_size": 5,
    "initial_threshold": initial_threshold,
    "percentile": 98,
    "max_percentile": 99,
    "smoothing": 0.8,
    "min_samples": 50,
    "safe_threshold": initial_threshold,
    "max_consecutive_drops": 5,
    "max_consecutive_ups": 5,
    "median_window": 5,
    "smooth_safety_th": True
}
ood_pool_size = len(data["Water"]) + len(data["Yogurt"]) + len(data["Egg"])
print(f"OOD pool size: {ood_pool_size}")
ratio_percentages = [
    (0.85, 0.15),
    (0.95, 0.05),
    (0.98, 0.02),
    (0.99, 0.01)
]
block_sizes = [50, 100, 200] # each blocks is a waves of data
block_sizes=[]
wave_patterns = { 'Standard': ['Test', 'Yogurt', 'Water', 'Egg'], 'FastSwitch': ['Test', 'Water', 'Yogurt', 'Egg', 'Test', 'Yogurt'] } #waves stream patters
tests = []
for id_pct, ood_pct in ratio_percentages:
    n_id = int(TOTAL_SAMPLES * id_pct)
    n_ood = int(TOTAL_SAMPLES * ood_pct)
    for replace in [True, False]:
        if not replace and n_ood > ood_pool_size:
            print(f"Skipping Random w/o Rep ({id_pct*100:.0f}%ID/{ood_pct*100:.0f}%OOD) - n_ood={n_ood} > pool={ood_pool_size}")
            continue

        label = f"Random {'w/' if replace else 'w/o'} Rep ({id_pct*100:.0f}%ID/{ood_pct*100:.0f}%OOD)"
        tests.append((label, lambda ni=n_id, no=n_ood, r=replace: generate_random_stream(data, n_test=ni, n_ood=no, replace=r), detector_params))

# Worst-case streams
for worst_ood_pct in [0.01, 0.02]:
    n_id = int(TOTAL_SAMPLES * (1 - worst_ood_pct))
    n_ood = int(TOTAL_SAMPLES * worst_ood_pct)
    if n_ood > ood_pool_size:
        print(f"Skipping Worst-Case Hard OOD ({100 - worst_ood_pct*100:.0f}%ID/{worst_ood_pct*100:.0f}%OOD) - n_ood={n_ood} > pool={ood_pool_size}")
        continue

    label = f"Worst-Case Hard OOD ({100 - worst_ood_pct*100:.0f}%ID/{worst_ood_pct*100:.0f}%OOD)"
    tests.append((label, lambda ni=n_id, no=n_ood: generate_worst_case_stream(data, centroids, n_test=ni, n_ood=no), detector_params))

print(f"Number of tests: {len(tests)}")
"""
# Random streams
for id_pct, ood_pct in ratio_percentages:
    n_id = int(TOTAL_SAMPLES * id_pct)
    n_ood = int(TOTAL_SAMPLES * ood_pct)
    for replace in [True, False]: # sampling form the embedding pool can be done with or with out replacement
        label = f"Random {'w/' if replace else 'w/o'} Rep ({id_pct*100:.0f}%ID/{ood_pct*100:.0f}%OOD)"
        #creation of all the possibile parameter combination of the random stream generator
        tests.append( ( label, lambda ni=n_id, no=n_ood, r=replace: generate_random_stream(data, n_test=ni, n_ood=no, replace=r), detector_params ) )

for worst_ood_pct in [0.01, 0.02]:
    n_id = int(TOTAL_SAMPLES * (1 - worst_ood_pct))
    n_ood = int(TOTAL_SAMPLES * worst_ood_pct)
    label = f"Worst-Case Hard OOD ({100 - worst_ood_pct*100:.0f}%ID/{worst_ood_pct*100:.0f}%OOD)"
    tests.append((label, lambda ni=n_id, no=n_ood: generate_worst_case_stream(data, centroids, n_test=ni, n_ood=no), detector_params))

print(f"Numer of tests: {len(tests)}")
"""
"""
results = {}
for name, generator, params in tests:
    stream_data, stream_labels = generator() #call the build_wave_stream or generate_random_stream for the stream creation
    res = start_test_phase(stream_data, stream_labels, params, name, val_dists, detector_params["min_samples"]) # labels 0 = ID 1 = OOD
    results[name] = res
"""
results = {}
for name, generator, params in tests:
    stream_data, stream_labels, stream_quality = generator()  # Ora ricevi 3 valori
    res = start_test_phase(stream_data, stream_labels, stream_quality, params, name, val_dists, detector_params["min_samples"])
    results[name] = res
print("\n" + "="*60)
print(" RECAP ")
print("="*60)
allowed_keys = [ "window_size", "batch_size", "smoothing", "percentile",  "safe_threshold", "smooth_safety_th" ]
parts = []
for key in allowed_keys:
    if key in detector_params:
        val = detector_params[key]
        formatted_val = f"{val:.2f}" if isinstance(val, float) else f"{val}"
        parts.append(f"{key}: {formatted_val}")
print(" | ".join(parts))

print("\n TB -> traffic blocked ------- TA -> traffic allowed")
"""
print(f"{'Test':<45} {'Acc':>8} {'Prec':>8} {'Rec':>8} {'F1':>8} \t {'TB':>8} \t {'TA':>8}  ")
for name, res in results.items():
    print(f"{name:<45} {res['acc']:8.4f} {res['prec']:8.4f} {res['rec']:8.4f} {res['f1']:8.4f} \t {res['TB']:8.4f}  \t{res['TA']:8.4f}  ")
"""
print(f"{'Test ':<38} {'Acc':>7} {'AUPRC':>7} {'FPR@95':>8} {'Prec':>7} {'Rec':>7} {'F1':>7} {'TB (%)':>8} {'TA (%)':>8}")
print("-" * 110)
for name, res in results.items():
    print(f"{name:<38} {res['acc']:7.4f} {res['auprc']:7.4f} {res['fpr95']*100:7.2f}% {res['prec']:7.4f} {res['rec']:7.4f} {res['f1']:7.4f} {res['TB']:7.2f}% {res['TA']:7.2f}%")

random_tests = [k for k in results if "Random" in k]
wave_tests = [k for k in results if "Wave" in k]

def status(names, label):
    if not names:
        return
    acc  = [results[n]['acc'] for n in names]
    prec = [results[n]['prec'] for n in names]
    rec  = [results[n]['rec'] for n in names]
    f1   = [results[n]['f1'] for n in names]
    print(f"\n--- {label} ---")
    print(f"Acc: {np.mean(acc):.4f} ± {np.std(acc):.4f}")
    print(f"Prec: {np.mean(prec):.4f} ± {np.std(prec):.4f}")
    print(f"Rec:  {np.mean(rec):.4f} ± {np.std(rec):.4f}")
    print(f"F1:   {np.mean(f1):.4f} ± {np.std(f1):.4f}")
"""
status(random_tests, "Test Random (basic)")
status(wave_tests, "Test Wave (basic)")

acc_list = [res['acc'] for res in results.values()]
prec_list = [res['prec'] for res in results.values()]
rec_list = [res['rec'] for res in results.values()]
f1_list = [res['f1'] for res in results.values()]

acc_mean, acc_std = np.mean(acc_list), np.std(acc_list)
prec_mean, prec_std = np.mean(prec_list), np.std(prec_list)
rec_mean, rec_std = np.mean(rec_list), np.std(rec_list)
f1_mean, f1_std = np.mean(f1_list), np.std(f1_list)

print("\n" + "="*60)
print(f"Average accuracy over all tests: {acc_mean:.4f} ± {acc_std:.4f}")
print(f"Average (OOD) precision over all tests : {prec_mean:.4f} ± {prec_std:.4f}")
print(f"Average (OOD) recall over all tests : {rec_mean:.4f} ± {rec_std:.4f}")
print(f"Average (OOD) F1-score over all the tests: {f1_mean:.4f} ± {f1_std:.4f}")

metriche = ['Accuracy', 'Precision', 'Recall', 'F1']
medie = [acc_mean, prec_mean, rec_mean, f1_mean]
std_dev = [acc_std, prec_std, rec_std, f1_std]

fig, ax = plt.subplots(figsize=(8, 6))
bars = ax.bar(metriche, medie, yerr=std_dev, capsize=5, color=['skyblue', 'lightgreen', 'lightcoral', 'gold'], alpha=0.8, edgecolor='black')
ax.set_ylabel('Average value')
ax.set_title(' Average performances \n(Error bars represent standard deviation) ')
ax.set_ylim([0, 1])
ax.grid(axis='y', alpha=0.3)
for bar, val in zip(bars, medie):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02, f'{val:.3f}', ha='center', va='bottom', fontsize=10)
plt.tight_layout()
"""
plt.show()

"""A percentile of 99% is very conservative rather than one of 95% so

window_size: 50 | batch_size: 5 | smoothing: 0.90 | percentile: 99 | safe_threshold: 0.40 | smooth_safety_th: True
TB -> traffic blocked ------- TA -> traffic allowed
Test                                               Acc     Prec      Rec       F1 	       TB 	       TA
Random w/ Rep (95%ID/15%OOD)                    0.9072   0.9521   0.4297   0.5922 	  92.9267  	  7.0733
Random w/o Rep (95%ID/15%OOD)                   0.9132   0.9560   0.4690   0.6293 	  92.2914  	  7.7086
Random w/ Rep (90%ID/10%OOD)                    0.9414   0.9394   0.5020   0.6544 	  94.0913  	  5.9087
Random w/o Rep (90%ID/10%OOD)                   0.9436   0.9275   0.5246   0.6702 	  93.8227  	  6.1773
Random w/ Rep (95%ID/5%OOD)                     0.9692   0.7632   0.6960   0.7280 	  94.5920  	  5.4080
Random w/o Rep (95%ID/5%OOD)                    0.9654   0.7500   0.5950   0.6636 	  95.4459  	  4.5541
Random w/ Rep (96%ID/4%OOD)                     0.9702   0.7111   0.6400   0.6737 	  95.6793  	  4.3207
Random w/o Rep (96%ID/4%OOD)                    0.9760   0.7426   0.7576   0.7500 	  95.1512  	  4.8488
Random w/ Rep (97%ID/3%OOD)                     0.9776   0.6901   0.6712   0.6806 	  96.5484  	  3.4516
Random w/o Rep (97%ID/3%OOD)                    0.9796   0.6860   0.7973   0.7375 	  95.8192  	  4.1808
Random w/ Rep (98%ID/2%OOD)                     0.9734   0.4675   0.7347   0.5714 	  96.2106  	  3.7894
Random w/o Rep (98%ID/2%OOD)                    0.9749   0.4737   0.7660   0.5854 	  96.2598  	  3.7402
Random w/ Rep (99%ID/1%OOD)                     0.9761   0.3235   0.9167   0.4783 	  96.6119  	  3.3881
Random w/o Rep (99%ID/1%OOD)                    0.9771   0.3281   0.8750   0.4773 	  96.8112  	  3.1888

### QoS and SLA of the Component
- **Mean:** The average embedding processing time. It provides a long-term overview of the system's efficiency
- **P95:** 95% of the execution times are lower than or equal to this value, only 5% are higher. Metric for real-time SLA (service level agreement)
- **P99:** Same principle as P95, but stricter (99% lower, 1% higher). Useful for isolating worst-case
- **Max:** Indicates the worst-case latency encountered during the benchmark
- **Std (Standard Deviation):** Measures the stability and predictability of the processing time. Lower values mean more stable performance
- **FPS (Frames Per Second):** The overall system throughput. It represents how many embeddings the system can process within a one-second time slot, calculated based on the mean latency
- **UpdCost (Update Cost):** Measures the specific overhead of the batch update operation. It is calculated as the mean time of steps with the update operation minus the mean time of steps without the update operation
"""

configs=[(50,5),(100,5),(100,10),(200,20),(500,50)]
results=[]
centroids=np.random.randn(100,512)
embeddings=np.random.randn(10000,512)
warmup=100
for window,batch in configs: # split the overall detector performance from the th update operation
    detector=RealTimeOODDetector(centroids,window_size=window,batch_size=batch, min_samples=warmup)
    for e in embeddings[:warmup]: #i don't want to consider the warm up phase
        detector.process(e)
    t, upd = [], []
    for i, e in enumerate(embeddings):
      s = time.perf_counter_ns()
      detector.process(e)
      t.append((time.perf_counter_ns()-s)/1e6) # store the time for process() operation  execution
      if (i+1) % batch == 0: #store also the process performance of a th update
        upd.append(t[-1])
    t, upd = np.array(t), np.array(upd)
    results.append([ window,batch, t.mean(), np.percentile(t,95), np.percentile(t,99), t.max(), t.std(), 1000/t.mean(),
#normal operation execute process() rather process()+ _update_threshold() for the th. update steps
    upd.mean()-np.delete(t,np. arange(batch-1,len(t),batch) ).mean() ]) # overhead cost of the update step (upd_mean - standard_mean_with_out_update_setps)
print(f"{'W':>5}{'B':>5}{'Mean':>10}{'P95':>10}{'P99':>10}{'Max':>10}{'Std':>10}{'FPS':>10}{'UpdCost':>10}")
for r in results:
    print(f"{r[0]:5}{r[1]:5}{r[2]:10.3f}{r[3]:10.3f}{r[4]:10.3f}{r[5]:10.3f}{r[6]:10.3f}{r[7]:10.1f}{r[8]:10.3f}")

"""The testing phase has been executed on my local pc, the task process has been scheduled on a specific process core.

However, small run-to-run variability are mainly due to operating-system background activity

taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.443     0.614     0.798     1.691     0.093    2255.3    -0.003
  100    5     0.622     1.151     1.731     2.693     0.283    1608.9     0.529
  100   10     0.591     1.122     1.521     2.728     0.247    1693.4     0.604
  200   20     0.603     1.034     1.651     2.476     0.238    1659.5     0.726
  500   50     0.511     0.789     1.204     2.209     0.159    1957.0     0.773
######################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.424     0.535     0.740     1.295     0.068    2361.1    -0.000
  100    5     0.707     1.366     1.995     4.419     0.351    1415.4     0.612
  100   10     0.492     0.897     1.090     2.117     0.170    2031.0     0.493
  200   20     0.486     0.902     1.167     2.918     0.179    2057.4     0.569
  500   50     0.525     0.940     1.271     3.025     0.198    1903.3     0.770
######################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.490     0.814     1.092     2.302     0.154    2039.0     0.004
  100    5     0.552     0.976     1.284     2.894     0.229    1810.2     0.482
  100   10     0.554     1.000     1.466     2.168     0.220    1804.4     0.578
  200   20     0.485     0.906     1.167     2.553     0.169    2060.2     0.589
  500   50     0.494     0.806     1.254     2.384     0.173    2022.6     0.753
#####################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.409     0.453     0.533     1.305     0.033    2445.3     0.001
  100    5     0.514     0.872     0.923     1.700     0.177    1944.1     0.431
  100   10     0.469     0.875     0.944     1.482     0.145    2130.6     0.461
  200   20     0.456     0.857     1.014     1.814     0.129    2191.8     0.530
  500   50     0.444     0.636     1.019     2.218     0.111    2252.8     0.623
#####################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.464     0.683     0.848     1.296     0.098    2154.3     0.001
  100    5     0.592     1.060     1.345     2.022     0.235    1690.6     0.500
  100   10     0.551     1.013     1.334     2.279     0.211    1814.2     0.567
  200   20     0.639     1.025     1.847     3.405     0.264    1565.7     0.788
  500   50     0.576     0.879     1.340     2.186     0.184    1734.9     0.854
####################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.490     0.756     1.006     2.048     0.131    2040.2     0.001
  100    5     0.595     1.057     1.498     2.757     0.252    1680.7     0.517
  100   10     0.522     0.953     1.228     2.322     0.199    1915.0     0.533
  200   20     0.489     0.923     1.151     1.974     0.163    2043.9     0.596
  500   50     0.460     0.680     1.105     2.364     0.136    2175.0     0.715
####################################################################################
taskset -c 1 python3 metrics.py
    W    B      Mean       P95       P99       Max       Std       FPS   UpdCost
   50    5     0.471     0.679     0.852     1.259     0.098    2124.4    -0.000
  100    5     0.562     0.960     1.221     1.933     0.210    1779.9     0.470
  100   10     0.509     0.920     1.115     1.825     0.176    1964.6     0.503
  200   20     0.531     0.944     1.261     2.367     0.196    1881.7     0.630
  500   50     0.494     0.750     1.145     1.983     0.145    2025.4     0.715

- Small window sizes achieve the lowest latency and highest throughput thanks to better cache locality and reduced memory-access latency

- Larger windows increase latency because percentile computation operates on a larger buffer, requiring more memory accesses

- Larger batch sizes improve overall performance by reducing the frequency of threshold updates, amortizing their computational cost over more embeddings

- Update Cost increases with the window and batch size, but its impact on throughput remains limited since updates are performed periodically

- P95 and P99 latencies remain below 2 ms in almost all configurations, demonstrating stable real-time performance

- Low standard deviation indicates predictable execution times

The performance results indicate a trade-off between CPU-bound and memory-bound configurations. Smaller windows and batch mainly stress the CPU due to frequent threshold updates, whereas larger windows become increasingly memory-bound because percentile computation operates on a larger working set.

### Consideration:

The threshold shape does not change significantly because the Out-of-Distribution (OOD) data is highly limited and hide the two Gaussian distributions. Indeed, there is a fluctuation along the safety threshold value itself.

In this case scenario, setting an accurate safety threshold is highly critical because it acts as the primary discriminating factor.

My Approaches:
- Upper Bound of the Validation Set Distance Distribution (Current Method): In a truly robust modeling scenario, the validation set represents the solid, inherent nature of the data and is not used for tuning the model weights. Therefore, a solid and well-structured validation set allows us to extract a reliable data distance distribution. Consequently, this safety threshold could become a new hyperparameter for the model.

- Define an Upper Bound Percentile on the Training Data Distance Distribution: (Alternative method).

# STAGE 5

Find out what happen to the model and distance distribution after a system retrain.

Now the model has been retrain with also the OOD data samples
"""

REPO_ID = "tomasconti/Drift_Detection"
print("Downloading native 512-D embeddings from HuggingFace")
path_train = hf_hub_download(repo_id=REPO_ID, filename="84C/train_embeddings_84C.npy")
path_val = hf_hub_download(repo_id=REPO_ID, filename="84C/val_embeddings_84C.npy")
path_test = hf_hub_download(repo_id=REPO_ID, filename="84C/test_embeddings_84C.npy")
test_embeddings_84C = np.load(path_test)
val_embeddings_84C = np.load(path_val)
train_embeddings_84C = np.load(path_train)

train_labels = train_generator.classes
tsne = TSNE( n_components=2, perplexity=50, learning_rate="auto", init="pca", random_state=42 )
embeddings_2d = tsne.fit_transform(train_embeddings_84C)
print("t-SNE shape:", embeddings_2d.shape)
plt.figure(figsize=(12,10))
scatter = plt.scatter( embeddings_2d[:,0], embeddings_2d[:,1], )
plt.title("t-SNE visualization of test set embeddings")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.show()

"""Are visible some new clusters into the embedding (ODD new clusters)"""

results = []
for linkage in ['ward', 'complete', 'average', 'single']:
    for k in range(75, 91):
        model = AgglomerativeClustering( n_clusters=k,linkage=linkage)
        labels = model.fit_predict(train_embeddings_84C)
        results.append({ "Linkage": linkage,"K": k,"Silhouette": silhouette_score(train_embeddings_84C, labels)})
df_results = pd.DataFrame(results)
plt.figure(figsize=(10,5))
sns.lineplot( data=df_results, x="K", y="Silhouette", hue="Linkage", marker="o")
plt.title("Agglomerative Clustering of embeddings")
plt.xlabel("Clusters")
plt.ylabel("Silhouette Score")
plt.grid()
plt.legend()
plt.show()

n_clusters = 84
cluster_model = AgglomerativeClustering( n_clusters=n_clusters, linkage='ward')
labels = cluster_model.fit_predict(train_embeddings_84C)
centroids = np.array([ train_embeddings_84C[labels == i].mean(axis=0) for i in range(n_clusters)])
print("Centroids shape:", centroids.shape)

all_data = np.concatenate( [train_embeddings_84C, centroids], axis=0 )
all_2d = TSNE( n_components=2, perplexity=50, random_state=42, init="pca").fit_transform(all_data)

train_2d = all_2d[:len(train_embeddings_84C)]
centroids_2d = all_2d[len(train_embeddings_84C):]

plt.figure(figsize=(12,8))
plt.scatter( train_2d[:,0], train_2d[:,1], s=15, alpha=0.4, label="Train embeddings" )

plt.scatter( centroids_2d[:,0], centroids_2d[:,1], marker="X", s=120, c="red", edgecolors="black", label="Cluster centroids" )

plt.title("t-SNE: Train embeddings + Agglomerative Centroids")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend()
plt.grid(True)

plt.show()

"""OOD clusters are now part of the system's semantic embeddings, making it possible to define new semantic anchor centroids"""

knn = NearestNeighbors(n_neighbors=1, metric="euclidean").fit(centroids)
data_embeddings = { "Train": train_embeddings_84C,"Val": val_embeddings_84C, "Test": test_embeddings_84C }
distances = {}
for name, emb in data_embeddings.items():
    flat_distances = knn.kneighbors(emb)[0].flatten()
    distances[name] = flat_distances

plt.figure(figsize=(10,6))

for name, dist in distances.items():
    sns.kdeplot(dist, fill=True, alpha=0.25, label=name)
    plt.axvline(np.median(dist), linestyle="--", label=f"{name} median")

plt.title("Distance to nearest centroid (K=1)")
plt.xlabel("Euclidean distance")
plt.ylabel("Density")
plt.grid(alpha=0.3)
plt.legend()
plt.show()

rows = []
for name, dist_list in distances.items():
    for d in dist_list:
        row_dict = { "Dataset": name, "Distance": d }
        rows.append(row_dict)

df_dist = pd.DataFrame(rows)

plt.figure(figsize=(10,5))
sns.boxplot(data=df_dist, x="Dataset", y="Distance") #required a dataframe
plt.title("Distance distribution to nearest centroid")
plt.grid(axis="y", alpha=0.3)
plt.show()

"""After retraining the ResNet CNN with the OOD samples, the model is now able to recognize the new clusters. New anchor centroids have been introduced for the distance calculation, which helps bring the test distance distribution into a stable state. We no longer see the old, two Gaussian distribution separating ID and OOD data. Thanks to the retraining, the system can now target the old OOD data, which has officially become part of the In-Distribution (ID) data"""